name: Test

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      node-image:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.runs-on }}
    container:
      image: ${{ inputs.node-image }}
    steps:
      - uses: actions/checkout@v4

      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@${{ inputs.pnpm-version }} --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test
